# Generated by Django 5.0.7 on 2024-07-23 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='foto/%Y/%m/%d'),
        ),
    ]
