# Generated by Django 5.0.7 on 2024-07-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_alter_veiculo_data_alter_veiculo_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='preco',
            field=models.FloatField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, max_length=250, upload_to='foto/%Y/%m/%d'),
        ),
    ]
