# Generated by Django 5.0.7 on 2024-07-24 20:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_veiculo_preco_alter_veiculo_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(blank=True, max_length=255, upload_to='attachments/%Y/%m')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='galeria.veiculo')),
            ],
        ),
    ]
