# Generated by Django 5.0.7 on 2024-08-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_imagemveiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.FloatField(blank=True, default=0, max_length=20, null=True),
        ),
    ]
