# Generated by Django 5.0.7 on 2024-08-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_alter_veiculo_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(blank=True, upload_to='veiculos/imagens'),
        ),
    ]
