# Generated by Django 5.0.7 on 2024-08-22 23:37

import apps.galeria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_veiculo_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemveiculo',
            name='imagem',
            field=models.ImageField(blank=True, max_length=255, upload_to=apps.galeria.models.caminho_imagens),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='foto',
            field=models.ImageField(upload_to='veiculos/imagens'),
        ),
    ]
