# Generated by Django 5.0.7 on 2024-08-22 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_imagemveiculo_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
